export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-elevated': 'var(--surface-2)',
        'border-subtle': 'var(--border-subtle)',
        border: 'var(--border)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        accent: 'var(--accent)',
        'neon-blue': 'var(--neon-blue)',
        'neon-violet': 'var(--neon-violet)',
        'neon-magenta': 'var(--neon-magenta)',
        'neon-cyan': 'var(--neon-cyan)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        push: 'var(--push)',
        pull: 'var(--pull)',
        legs: 'var(--legs)',
        core: 'var(--core)',
      },
      backgroundImage: {
        'grad-primary': 'var(--grad-primary)',
        'grad-primary-soft': 'var(--grad-primary-soft)',
        'grad-cyan': 'var(--grad-cyan)',
        'grad-push': 'var(--grad-push)',
        'grad-pull': 'var(--grad-pull)',
        'grad-legs': 'var(--grad-legs)',
        'grad-core': 'var(--grad-core)',
      },
      boxShadow: {
        'glow-accent': 'var(--glow-accent)',
        'glow-blue': 'var(--glow-blue)',
        'glow-magenta': 'var(--glow-magenta)',
        card: 'var(--shadow-card)',
        nav: 'var(--shadow-nav)',
      },
      borderRadius: {
        sm: '10px',
        md: '14px',
        lg: '20px',
        xl: '28px',
        pill: '999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'monospace'],
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pop: {
          '0%': { opacity: '0', transform: 'scale(0.92)' },
          '60%': { opacity: '1', transform: 'scale(1.03)' },
          '100%': { transform: 'scale(1)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(139,92,246,0.5)' },
          '50%': { boxShadow: '0 0 22px 4px rgba(139,92,246,0.55)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.4s cubic-bezier(0.22, 1, 0.36, 1) both',
        pop: 'pop 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
